[package]
authors = ["Matt Vertescher <mvertescher@gmail.com>"]
edition = "2018"
name = "hello-world"
version = "0.1.0"

[dependencies]

[profile.dev]
panic = 'abort'

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
